### ISSUE TITLE
Register your admin account

### ISSUE THREAD

**Issue by David-Baron** [benjamw/battleship#2]
Hi
Register your admin account
It's not easy!!!
response is: sorry, but we are not accepting new registration at this time :(

Allow new users to register  = 1

Would you help me pls

**Comment by benjamw** [comment]
Hi, sorry you're having problems.
Can you give me any more detail on this issue?

**Comment by benjamw** [comment]
Ok, so it looks like the issue was because the table prefixes in the sample config file, and the install.sql file were not the same.

I've fixed the issue in the repo.  To fix the issue on your system, edit your `/includes/config.php` file and change the `$game_prefix` to `bs2_`.

**Comment by David-Baron** [comment]
Hi Ben,
Tks for reponses then....
this issue is closed i open an other
