### ISSUE TITLE
Bugs fix for install

### ISSUE THREAD

**Issue by David-Baron** [benjamw/battleship#3]
FIX_IT=> config.php.sample           INSERT INTO `bs2_settings` (`setting`, `value`, `notes`, `sort`) VALUES
                                    ('expire_finished_games', '7', 'Number of days until finished games are deleted (0 = off)', 128);
                                    
         FIX_IT=> includes/config.php.sample   on line 43                       
         define('T_BATTLESHIP'   , $master_prefix . $game_prefix . 'bs_player'); // the battleship player data table
                  BY
                  define('T_BATTLESHIP'   , $master_prefix . $game_prefix . 'player'); // the battleship player data table

To enjoy a nice install :)

Thank for your job
an sry for my english i'm french

@++

**Comment by benjamw** [comment]
That extra prefix for the player table is deliberate, and is part of the base table name. Please do not change that.

As for the other (top) fix, I'm not sure what you are fixing exactly.

**Comment by benjamw** [comment]
The top fix has been committed to the repo. Thanks.
